#-------------------------------------------------------------------------------
#  CONFIGURATION FILE
#-------------------------------------------------------------------------------
# project name:  Systems Administration
# file name:     .bashrc
# modified:      January 17, 2018
# description:   A 'bashrc' account setup file.

#-------------------------------------------------------------------------------
# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#-------------------------------------------------------------------------------
# NOTE: This TERM setting needs to exist for 'zenburn' colors to work
#       properly in vim.
export TERM=xterm-256color

#-------------------------------------------------------------------------------
# Set 'most' as my current pager.  'most' is a replacement for more or less,
# and displays the man pages in color.
export PAGER='most'

#-------------------------------------------------------------------------------
# Set colors
if type -P dircolors>/dev/null ; then
        if [[ -f ~/.dir_colors ]] ; then
            eval $(dircolors -b ~/.dir_colors)
        elif [[ -f /etc/DIR_COLORS ]] ; then
            eval $(dircolors -b /etc/DIR_COLORS)
        fi
fi

#-------------------------------------------------------------------------------
# END OF FILE
#-------------------------------------------------------------------------------
