#-------------------------------------------------------------------------------
#  CONFIGURATION FILE
#-------------------------------------------------------------------------------
# project name:  Systems Administration
# file name:     .profile
# modified:      January 17, 2018
# description:   A 'profile' account setup file.

#-------------------------------------------------------------------------------
# Set the umask . . .
umask 022

#-------------------------------------------------------------------------------
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

#-------------------------------------------------------------------------------
# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

#-------------------------------------------------------------------------------
# END OF FILE
#-------------------------------------------------------------------------------
